#!/usr/bin/env node
/**
 * Build Harbor Agents for Figma.
 *
 * - Cuts IDE panel modules via build-panel-figma.js
 * - Writes ui.html (manifest `"ui"` → `__html__` when Figma injects it)
 * - Also embeds the same HTML into code.js as chunked strings (`__HTML_UI__`).
 *   Dev Mode often leaves `__html__` empty for large UI files; a single giant
 *   string literal can crash the plugin environment — chunks avoid both issues.
 */

const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const root = path.join(__dirname, "..");
const figmaDir = path.join(root, "figma");
const distDir = path.join(figmaDir, "dist");
/** Raw HTML chars per JS string literal (keeps each literal modest). */
const HTML_CHUNK = 6000;

function ensureDist() {
  if (!fs.existsSync(distDir)) fs.mkdirSync(distDir, { recursive: true });
}

function extractCss() {
  execFileSync(process.execPath, [path.join(__dirname, "extract-figma-css.js")], {
    cwd: root,
    stdio: "inherit",
  });
}

function buildUiPanel() {
  execFileSync(process.execPath, [path.join(__dirname, "build-panel-figma.js")], {
    cwd: root,
    stdio: "inherit",
  });
}

function writeUiHtml() {
  const shellHtml = fs.readFileSync(
    path.join(figmaDir, "ui.shell.html"),
    "utf8"
  );
  const css = fs.readFileSync(path.join(figmaDir, "ui.css"), "utf8");
  let uiJs = fs.readFileSync(path.join(distDir, "ui.js"), "utf8");
  uiJs = uiJs.replace(/<\/script/gi, "<\\/script");
  const html = shellHtml
    .replace("<!-- FIGMA_CSS -->", `<style>\n${css}\n</style>`)
    .replace("<!-- FIGMA_JS -->", `<script>\n${uiJs}\n</script>`);
  fs.writeFileSync(path.join(figmaDir, "ui.html"), html, "utf8");
  fs.writeFileSync(path.join(distDir, "ui.html"), html, "utf8");
  return html;
}

function htmlToChunkedConst(html) {
  const parts = [];
  for (let i = 0; i < html.length; i += HTML_CHUNK) {
    parts.push(JSON.stringify(html.slice(i, i + HTML_CHUNK)));
  }
  return (
    "/* generated by scripts/build-figma.js - do not edit */\n" +
    "var __HTML_UI__ = [\n  " +
    parts.join(",\n  ") +
    "\n].join(\"\");\n"
  );
}

function writeCodeJs(html) {
  const logicPath = path.join(figmaDir, "code.logic.js");
  if (!fs.existsSync(logicPath)) {
    throw new Error("Missing figma/code.logic.js");
  }
  const logic = fs.readFileSync(logicPath, "utf8");
  const out = htmlToChunkedConst(html) + logic;
  fs.writeFileSync(path.join(figmaDir, "code.js"), out, "utf8");
  fs.writeFileSync(path.join(distDir, "code.js"), out, "utf8");
  return { bytes: out.length, chunks: Math.ceil(html.length / HTML_CHUNK) };
}

function copyManifest() {
  fs.copyFileSync(
    path.join(figmaDir, "manifest.json"),
    path.join(distDir, "manifest.json")
  );
  fs.writeFileSync(
    path.join(distDir, "CUT_LIST.txt"),
    [
      "Harbor Figma UI cut list (not in ui.js):",
      "- media/src/panel/* IDE modules",
      "- JetBrains polyfills, MCP/Skills, SCM/commit UI",
      "- Cline / sidecar",
      "",
      "Runtime: ui.html + chunked __HTML_UI__ fallback in code.js (Dev Mode).",
      "",
    ].join("\n"),
    "utf8"
  );
}

ensureDist();
extractCss();
buildUiPanel();
const html = writeUiHtml();
const { bytes, chunks } = writeCodeJs(html);
copyManifest();
console.log("Figma plugin ready:");
console.log("  Import: figma/manifest.json");
console.log(
  "  main:   figma/code.js (" +
    bytes +
    " bytes, " +
    chunks +
    " HTML chunks); ui: figma/ui.html (" +
    html.length +
    " chars)"
);
